### ISSUE TITLE
Addressing accessibility for opening a New Tab

### ISSUE THREAD

**Issue by thomas-michaud** [markjaquith/page-links-to#111]
It would be helpful for Accessibility to add in text (readable by screen readers) if a Custom URL is selected to **Open this link in a new tab**.

- Add in a `span` element after the anchor tag
- The class could use WordPress' built in `.screen-reader-text`

Example:
`<a href="https://another.site.example.com/whatever" target="_blank">Page Name</a><span class="screen-reader-text"> (opens in a new tab)</span>`

**Comment by markjaquith** [comment]
Good idea! I think I'm going to use `aria-label` for this, which is I believe what Gutenberg ended up doing.
