### ISSUE TITLE
Trying to get property 'ID' of non-object: page-links-to/classes/plugin.php:661

### ISSUE THREAD

**Issue by MadtownLems** [markjaquith/page-links-to#112]
My error log is pretty full with instances of the following notice.

It comes from this line:
$meta_link = self::get_link( $post->ID );

I'm not sure exactly what causes. I could try to dig deeper, but thought you might have a better idea (or just add some checking that $post is in fact a post object before proceeding).

Let me know your thoughts please!

**Comment by markjaquith** [comment]
This is odd. Something must be calling a filter but not passing the required data. Probably another plugin doing something wrong, but I can just make my code a little bit more defensive, such that it bails if it doesn't get a post, as expected.
