### ISSUE TITLE
URL not saved for CPT and Gutenberg because early meta key registration

### ISSUE THREAD

**Issue by meszarosrob** [markjaquith/page-links-to#114]
The custom URL is not saved for a CPT that is registered after the `init` hook.

## Steps to reproduce

1. Spin up a fresh WP install
2. Install Page Links To plugin
3. Create a Twenty Twenty child theme and activate it
4. Register a new post type from the child theme
5. Set up a custom URL for the custom post type

`$post_type_names` value with Xdebug: https://dsc.cloud/6455b1/TfCd9H5ogxRO.png

📹 https://dsc.cloud/6455b1/JzXl5ruLnCC9.mp4

#### Tested with

- WordPress `5.4.2`
- Twenty Twenty parent theme `1.4`
- Page Links To `3.3.3`
- PHP `7.4.2`

## Cause

The problem seems to be that the meta key registration happens before the `init` hooks is fired.

https://github.com/markjaquith/page-links-to/blob/e8f673df9ebfcf727a14e32f00d462cd372848ce/classes/plugin.php#L191-L199

In most of the tutorials and the on WP docs the recommended way is to register the post types after the `init`.

> Note: Post type registrations should not be hooked before the ‘init’ action.

https://developer.wordpress.org/reference/functions/register_post_type/

---

#### Scaffold a child theme

```bash
wp scaffold child-theme twentytwenty-child --parent_theme=twentytwenty
```

#### Register a custom post type

```php
function book_setup_post_type() {
    $args = array(
        'public'    => true,
        'label'     => __( 'Books', 'twentytwenty-child' ),
        'menu_icon' => 'dashicons-book',
        'show_in_rest' => true
    );
    register_post_type( 'book', $args );
}

add_action( 'init', 'book_setup_post_type' );
```

**Comment by meszarosrob** [comment]
Meanwhile, this can be solved by registering the meta keys manually for the CPT.

```php
add_action(
    'page_links_to_init',
    static function (CWS_PageLinksTo $cwsPageLinksTo) {
        $cwsPageLinksTo->register_meta($cwsPageLinksTo::LINK_META_KEY, 'your_custom_post_type');
        $cwsPageLinksTo->register_meta($cwsPageLinksTo::TARGET_META_KEY, 'your_custom_post_type');
    }
);
```

`page_links_to_init` is a hook provided by the plugin. I'm using that, so I can get access to meta key constants.

**Comment by ukmgranger** [comment]
I have the same problem.  Not managed to fix it yet with my rubbish coding.
