### ISSUE TITLE
Is it possible that this plugin is vulnerable to a redirection attack?

### ISSUE THREAD

**Issue by wildfire20uk** [markjaquith/page-links-to#121]
Hi Mark,

I'm working on a cyber incident where a client is suffering a repeated redirection type attack and I am wondering if there is any chance that this plugin is the issue? It's unlikely but I'm trying to cover all the bases.

Please get in touch.

**Comment by markjaquith** [comment]
Unlikely. It only redirects to the URLs that the publisher has specified. There's no way for an attacker to use this plugin to redirect someone to an arbitrary URL.

**Comment by wildfire20uk** [comment]
Thanks, looks like another plugin that's the issue, thanks for the response
anyway. Please closed/delete the issue.
