### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by LabLover** [markjaquith/page-links-to#21]
Would there be anyway to allow for assignment of a CSS class to the redirect link?

For Example

Current link
```
<a target="_blank" href="http://compuaidusa.com/?p=239&amp;content-only=1&amp;css=1&amp;width=600&amp;height=550" title="Entertainment">Entertainment</a>
```
Link with class
```
<a class="thickbox" target="_blank" href="http://compuaidusa.com/?p=239&amp;content-only=1&amp;css=1&amp;width=600&amp;height=550" title="Entertainment">Entertainment</a>
```
This will enable the ability to open posts in a Thickbox or Fancybox directly from a list of posts in a megamenu.

Is there a realistic possibility this enhancement could be incorporated?

Thanks very much for this fine plugin!

**Comment by markjaquith** [comment]
There's no clean way for me to do this, as I only have control over the URL. I don't have access to manipulate classes or other HTML attributes. I'm just filtering the URL.
