### ISSUE TITLE
Find a better way of opening links in a new tab

### ISSUE THREAD

**Issue by markjaquith** [markjaquith/page-links-to#22]
I'm tired of having to support themes that load async content or something else and thus skip being noticed by PLT and links don't open in a new tab when specified.

The issue is that all I have control over is the URL output. I can't add a class or anything. And if I do something clever like use a fake protocol or add a URL parameter, that will interfere with SEO for that URL.

One option is to skip the logging, and always output the full array of "new tab" URLs. But that'll bloat the page if you have a huge number of "in a new tab" links. And it'll slow it down doing all those checks.

One thing I could do is append `#new_tab` to the end of the URL, and then have code that on load, removes that, and makes the links open on a new tab. And then I could monitor clicks on the fly to deal with content added after the fact. Google ignore hash fragments in URLs by default.

**Comment by markjaquith** [comment]
* [ ] need to clean up the inline JS stuff.

**Comment by jb510** [comment]
The object buffer is interfering with WP Retina 2X's object filter for using picturefill.js for retina images.  Two object buffers trying to run at the same time.  I told Jordy, guessing he might chime in here.

Took me a while to figure out because I had no idea page-links-to even ran JS...  

I know "decision over options" but I have no need to force links to open in a new window, maybe this should be optional.

**Comment by jb510** [comment]
Uh, note...  I think I was really unclear above...  The issue I'm having is with the object buffer cloning jQuery to jQueryWP.  Which seems to be so that you can trust jQuery is available to your new tab code.

https://cloudup.com/cRZ9ZWgzGTw

**Comment by markjaquith** [comment]
`ob_` stands for "output buffer”, not "object". ☺

What is probably happening is overlapping sandwiches. I implemented it the way I did so that my ob would only apply to the `<head>` section. But if that is causing issues I might just have to ob the whole page.

**Comment by jb510** [comment]
I mistype that a lot...  :)  

He's trying to get "the whole page", which he actually needs to do (wish WP had a filter) but he is starting at wp_head and ending at wp_footer.  I prefer the narrow focus of yours.

It's just seems unnecessary to me these days, theme devs seem to be a lot better about respecting jQuery...  or something that could be optional.  Perhaps a checkbox for "jQuery compatibility mode for poorly coded themes".

**Comment by michaelaris** [comment]
Yep, I'm having this issue with my Jobify Theme running WP Job Manager... my listings aren't opening in a new tab.
