### ISSUE TITLE
Override HTTPS linking

### ISSUE THREAD

**Issue by davemcphee** [markjaquith/page-links-to#29]
When I access my wordpress site in http, the Page Links To url works as expected - it redirects to the set custom url, http://theSpecificiedUrl

When I access the main site in https, the Page Link To url is automatically changed to link to https://theSpecificiedUrl

I understand this is probably working as designed, is there a way to override this? A way to have that particular link always point to an http endpoint, no matter how the original site is accessed?

**Comment by markjaquith** [comment]
I cannot duplicate this issue.

1. My site URL: `https://plugins.test/`
2. Page links to: `http://google.com/` (**no** "s")
3. Page link in nav menu: `http://google/com/` (**no** "s" added)

Please reopen if you're still experiencing this issue and give me some more information on how to reproduce it.
