### ISSUE TITLE
Links not open in new tab

### ISSUE THREAD

**Issue by thule179** [markjaquith/page-links-to#32]
Even though "Open this link in a new tab" is selected, the link wouldn't open in a new tab :'(

**Comment by gordonreedjones** [comment]
same issue, though it only occcurs when the used in conjuction with pagination. i have a site where blog posts load on page scroll. those posts (title, image, excert, date) that load initially work fine (title links offsite, new window). but the posts that load on scroll do not open in new window, even though they are set to do so.
