### ISSUE TITLE
Change default cws_links_to value to placeholder text?

### ISSUE THREAD

**Issue by apmatthews** [markjaquith/page-links-to#33]
The meta box auto populates the cws_links_to field with "http://" when the field is empty. I understand this is a helpful reminder for people to include http://, but it always has to be deleted unless you are manually typing out an absolute URL. We have had a few cases of someone copying and pasting a full URL (which will typically already includes the protocol) and forgetting to delete the default http:// text. Of course this breaks the URL.

What are your thoughts on setting "http://" as the placeholder attribute on the input rather than the default value? I'm happy to PR if you think this would make sense.

**Comment by markjaquith** [comment]
Good idea! Done.

The `placeholder` attribute didn't have good browser support when I first wrote this. (Wow, that was a long time ago!)
