### ISSUE TITLE
Remove inline code

### ISSUE THREAD

**Issue by gmariani** [markjaquith/page-links-to#34]
Can you please convert this to a queue-able script? It messes up with caching plugins and jQuery when it's deferred.

**Comment by gmariani** [comment]
Well either that or don't rely on jquery to select the elements. I mean, yo use jquery to check if it's inArray, the body is clicked and if attributes are set. Should not be difficult to remove that dependency

**Comment by markjaquith** [comment]
Yeah, I agree that the jQuery dependency should be removed. It also causes problems when some theme enqueues its own (really old) version of jQuery.
