### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by webmandesign** [markjaquith/page-links-to#35]
Hi Mark,

I've added Slovak translation to the plugin via https://translate.wordpress.org/projects/wp-plugins/page-links-to 

Please [ask Polyglots team](https://make.wordpress.org/polyglots/tag/editor-requests/) to add it in.

More on how to get the plugin into Polyglots at:
* https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/#sample-post
* https://make.wordpress.org/meta/handbook/documentation/translations/

Thanks and regards,

Oliver

**Comment by markjaquith** [comment]
I've made this request. Thanks!
