### ISSUE TITLE
metabox title and notice text should use "...{$post_type_obj->labels->singular_name}..." instead of "...Page..."

### ISSUE THREAD

**Issue by pbiron** [markjaquith/page-links-to#36]
Since Page Links To works for all post_types for which `'show_ui' => true` (and not just pages), the title of the metabox and the text in the notice should use the `singular_name` label of the post_type in question, instead of always using "...Page...", as it could be "disconcerting" to admin users who are editing a "Movie", etc and see something on screen that mentions "Page".

Attached is a patch that accomplishes this.

Two things to note about this patch:

1. there should be some error checking on the return value(s) of the 2 calls to `get_post_type_object()`...I'll leave that to you :-)
2. the change in `notify_of_external_link()` relies on the WP `global $typenow`.  I couldn't figure out a way to pass the current post to that func...maybe you can

[patch.zip](https://github.com/markjaquith/page-links-to/files/811537/patch.zip)

**Comment by markjaquith** [comment]
Hmm. There are a few issues here. One, is that this sort of compound title can't be translated. You can't pass a dynamic value to a translation string, as we don't know what the value will be until runtime. And if you use a token, you'll get oddities in certain languages where the rest of the sentence will have to change based on the gender of the subject of the sentence.

Next, there is the whole thing that the name of the plugin is "Page Links To". It should be thought of in the sense of "page view" and not "WordPress `post_type = 'page'`). That is, a `post_type` of `'movie'` still has a web **page** where it is viewed.

I tried to make a nod in favor of "this can be anything" by saying "this **content** is pointing to a custom URL".

**Comment by pbiron** [comment]
I hadn't thought about the translation aspect.

OK, it was just a thought.
