### ISSUE TITLE
Problems in Setting Up Twitter Card

### ISSUE THREAD

**Issue by CynthiaBeauty** [markjaquith/page-links-to#37]
I love this plugin because I run a news aggregator site that uses algorithms to pull together all the relevant articles around a specific development. I then write custom summaries based on all the articles, but assign the best article as the lead and give it the page-links-to link.

However, in trying to set up a twitter card for my blog posts, I need to point to a permalink that references my specific blog post in order for the twitter card to work for individual posts.

Can you recommend a method for doing this? I'm having trouble. If I construct a URL that says www.example.com/date/post id, I can go directly to my blog post in a browser. I should be able to do the same thing for Twitter cards. 

Do I need to create a filter to do this? Any suggestions would be greatly appreciated.

Thank you so much!

**Comment by markjaquith** [comment]
@CynthiaBeauty The next version of the plugin will have a function called `plt_get_original_permalink()` which will return the original permalink.

What are you using for Twitter cards? We might need to add filters to override the URL that it produces.

**Comment by CynthiaBeauty** [comment]
LOL! I ended up hiring a developer to help me figure out a new system.

**Comment by markjaquith** [comment]
Ha. Well, I'd meant to do this anyway. Just dusting off some very old tickets. Thanks for the reply!
