### ISSUE TITLE
Ukrainian translation suggestion

### ISSUE THREAD

**Issue by xrobachok** [markjaquith/page-links-to#38]
Hi Mark,

I've added [Ukrainian translation](https://translate.wordpress.org/projects/wp-plugins/page-links-to/stable/uk/default) to your plugin via https://translate.wordpress.org/projects/wp-plugins/page-links-to

Please [ask Polyglots team](https://make.wordpress.org/polyglots/tag/editor-requests/) to add it in.

More on how to get the plugin into Polyglots at:

- https://make.wordpress.org/polyglots/handbook/rosetta/theme-plugin-directories/#sample-post
- https://make.wordpress.org/meta/handbook/documentation/translations/

Thanks!

**Comment by markjaquith** [comment]
I've made this request. Thanks!
