### ISSUE TITLE
Missing new-tab.js

### ISSUE THREAD

**Issue by gnosisgithub** [markjaquith/page-links-to#39]
Both distributions:
https://github.com/markjaquith/page-links-to/t
https://wordpress.org/plugins/page-links-to/
missing the following file:
.../wp-content/plugins/page-links-to/js/new-tab.js

So for example:
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - http://.../wp-content/plugins/page-links-to/js/new-tab.js

**Comment by markjaquith** [comment]
The file is `new-tab.min.js`

https://github.com/markjaquith/page-links-to/blob/242cd2a7a36bcb37a371861208b696f4443c08f5/page-links-to.php#L152

Is it possible that your plugin install has an older version of `page-links-to.php` ?

**Comment by gnosisgithub** [comment]
absolutely not. I actually re-downloaded from Wordpress repo (do your two versions (github and WP match?) . To resolve, I created a fake.

**Comment by markjaquith** [comment]
I'm not sure why anything is trying to load this file. Do you have a caching plugin like W3 Total Cache that is doing minification/concatenation?

**Comment by gnosisgithub** [comment]
My theme (basic themify) performs minification:
https://themify.me/themes/basic

**Comment by markjaquith** [comment]
Yeah, so that's probably the issue.
