### ISSUE TITLE
IE Error SCRIPT438: Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by roxlife** [markjaquith/page-links-to#41]
SCRIPT438: Object doesn't support property or method 'from'
File: new-tab.min.js, Line: 2, Column: 130

I hate Internet Explorer!

**Comment by markjaquith** [comment]
Doh.

<img width="511" alt="screen shot 2018-06-07 at 10 51 23 pm" src="https://user-images.githubusercontent.com/353790/41136685-5c55fe28-6aa5-11e8-89c5-866ba7226a0c.png">

I shall research what Babel incantation I have to babel to remedy this. :smile:

**Comment by roxlife** [comment]
Thanks so much dick.

**Comment by markjaquith** [comment]
> Thanks so much dick.

Uh. Is there some missing punctuation there? I can't fathom why you'd be calling me a dick.

**Comment by roxlife** [comment]
Lol. I'm sorry. I think "dick" was a product of fat thumbs, autocorrect and
my slight inebriation at that moment. It was supposed to say, "Thanks so
much Mark."
Sorry about that!

**Comment by markjaquith** [comment]
Ha, well — cheers.

Version `2.10.2` should fix this issue.
