### ISSUE TITLE
My email

### ISSUE THREAD

**Issue by claytoncollie** [markjaquith/page-links-to#47]
Hey, I sent you a Google Forms about feature requests and didnt give you my email to beta test.  Thanks for building this plugin and keeping it active!

clayton.collie@contentpilot.com

**Comment by markjaquith** [comment]
Thanks Clayton! We're thinking of starting up a mailing list. Would it be alright if we add you to that?

**Comment by claytoncollie** [comment]
for sure!

**Comment by claytoncollie** [comment]
for sure!

*Clayton Collie*
clayton.collie@gmail.com
214-577-6712
