### ISSUE TITLE
Version 2.1.1 gives 404 errors when configured on page

### ISSUE THREAD

**Issue by ciacciojon9999** [markjaquith/page-links-to#49]
Every page using this plugin to redirect gives a 404 error when you navigate to the custom URL.

**Comment by markjaquith** [comment]
Odd. Cannot reproduce that issue. What do pages show if you **don't** point them to an external URL? Page Links To doesn't do anything special here... it just hooks in as the page is loading and redirects. It doesn't itself set up the rewrite rule for the page — WordPress itself does that.

**Comment by markjaquith** [comment]
Please re-open if you have new information!
