### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by panteror** [markjaquith/page-links-to#50]
Hi,

It's the first time i install your plugin (version 2.11.1). I have error 404 on link set in page link configuration of the article. The new link and old original link not working.

I use wordpress 4.9.6.

The original article : http://www.dowfrance.com/2017/06/presentation-days-of-war/
The page link setting : http://www.dowfrance.com/presentation-days-of-war/

It's deactivate now, i can reactivate if you want to do some tests.

Thanks

**Comment by markjaquith** [comment]
Hmm. You might be confused about how this works. If you point `dowfrance.com/2017/06/presentation-days-of-war/` to `dowfrance.com/presentation-days-of-war/`, all place where it shows a link will show `dowfrance.com/presentation-days-of-war/`, but that doesn't mean that `dowfrance.com/presentation-days-of-war/` will be a working URL. You have to point your content to a working URL. If you create a page called "Presentation Days of War", it should have the URL of `dowfrance.com/presentation-days-of-war/` at which point your "placeholder" `dowfrance.com/2017/06/presentation-days-of-war/` will point to it.

**Comment by panteror** [comment]
Thanks, exactly i was confused.
