### ISSUE TITLE
3.0.0 upgrade causes error message

### ISSUE THREAD

**Issue by lnkbrw** [markjaquith/page-links-to#54]
I just updated to the v.3.0.0 plugin this morning, using the built in "Upgrade" function from the Wordpress Plug-ins setting page.

Now my page presents this error in the top of every page.

`Warning: Missing argument 3 for CWS_PageLinksTo::wp_list_pages() in /home/my_blogs_directory_name/public_html/blog/wp-content/plugins/page-links-to/classes/plugin.php on line 650`

I am on WP 4.9.7 using a custom theme made in Artisteer. 

Installed active plugins are:

- Aksimet Anti-Spam 4.0.8
- Blogroll Links 2.3
- Duplicate Post 3.2.2
- Easy Logo Slider 1.2.1
- Exclude Pages from Navigation 1.9.2
- Google Photos & Picasa Viewer 3.0.13
- Jetpack 6.3.2
- Page Links To 3.0.0
- Responsive Lightbox & Gallery 2.0.5
- Simple Calendar 3.1.18
- TinyMCE Advanced 4.7.11
- WPtouch Mobile Plugin 4.3.28

I'm browsing from Chrome but it looks like it does it in all browsers.

**Any help fixing it, or a .zip of the prior version, would be appreciated.** (Edit: I just found the 2.11.0 .zip in the past Commits list.)

**Comment by lnkbrw** [comment]
Thanks so much! :-) 

I renamed the plugin folder to page-links-to-3-0-0 and created a new page-links-to folder with the old version, everything is back to normal.

**Comment by markjaquith** [comment]
Can you upload the code for `Exclude Pages from Navigation 1.9.2` somewhere? I couldn't find it in the plugin directory. I have a hunch that this plugin is calling the `wp_list_pages` filter with two arguments instead of three.

**Comment by lnkbrw** [comment]
Uploaded .zip to  https://ufile.io/r526y 

Thanks!

**Comment by markjaquith** [comment]
Hmm. That doesn't look like the culprit. In any case, I'll just practice some defensive coding.

Let me know if this version fixes it for you: https://github.com/markjaquith/page-links-to/archive/master.zip

**Comment by lnkbrw** [comment]
It looks like that copy of 3.0.1 beta 1 works just fine, no error message! Thank you! :-)

**Comment by markjaquith** [comment]
Great! This will be in the next release.
