### ISSUE TITLE
 Open this link in a new tab not working in visual composer post grid

### ISSUE THREAD

**Issue by moodyjive** [markjaquith/page-links-to#56]
Love the plugin and have used it flawlessly in many Wordpress sites. When using Visual Composer post grid, the custom url will load but ignore the "open this link in a new tab"

**Comment by moodyjive** [comment]
ACtually

**Comment by markjaquith** [comment]
So that VC class forces it to NOT open in a new tab? Like, it's fighting with my plugin?

**Comment by moodyjive** [comment]
Yeah I found a thread on Theme forest and this is what Visual Composer said: "Hello, The issue is due to vc_gitem-link class which does not support opening the link in a new tab. You can target it html custom js to remove the class added to it."

https://codecanyon.net/item/visual-composer-page-builder-for-wordpress/242431/comments?page=917

**Comment by moodyjive** [comment]
Happy to send you the email privately

**Comment by markjaquith** [comment]
Ah, thanks. The thread had a website where I could see the code that causes it.
