### ISSUE TITLE
404 issue!

### ISSUE THREAD

**Issue by mbnoimi** [markjaquith/page-links-to#58]
Hi,

Whenever I try to create a new custom link it points to "This page could not be found!"

![image](https://user-images.githubusercontent.com/284547/45611040-c3d8dc80-ba66-11e8-973f-fa1023855976.png)

![image](https://user-images.githubusercontent.com/284547/45611057-cf2c0800-ba66-11e8-945c-3b433d25747e.png)

![image](https://user-images.githubusercontent.com/284547/45611108-ee2a9a00-ba66-11e8-97ec-9dab87938155.png)

Both links don't work!
https://alternativia.com/test/testo/
https://alternativia.com/test/testo-rep/

I use:
* WordPress 4.9.8
* [OceanWP](https://wordpress.org/themes/oceanwp/) theme

**Comment by markjaquith** [comment]
This plugin doesn't create the destination URL. There needs to be content there already. So "testo" is pointing to "testo-rep", but beacuse "testo-rep" is on your site, and isn't created, WordPress gives you a 404.
