### ISSUE TITLE
Gutenberg Support?

### ISSUE THREAD

**Issue by billerickson** [markjaquith/page-links-to#59]
When editing a page with Gutenberg, the Page Links To metabox does not appear:

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/1b1o3F383j0A3Y131T1g/Screen%20Shot%202018-11-09%20at%206.57.09%20AM.png?X-CloudApp-Visitor-Id=1470414&v=a5b8b84b)

Editing the same page with the Classic Editor displays the metabox: 

![screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/1K3D3g3d022O3S1m3C06/Screen%20Shot%202018-11-09%20at%206.58.28%20AM.png?X-CloudApp-Visitor-Id=1470414&v=01d7073b)

**Comment by dhuyck** [comment]
As a quick patch, I added these three lines to my downloaded version of the plugin in the `is_supported_post_type()` method (added as lines 380-382):
```
	if ( is_object( $type ) ) {
		$type = $type->id;
	}
```

This will show the metabox properly, but there would be additional work to make the ajax/React code update the notices properly in Gutenberg.

**Comment by dhuyck** [comment]
I did a little further work to make admin notices work in WP5+. It's a little raw and optimized to our installation (where we can assume browser up-to-date-ness), but it's working. I have updated the `notify_of_external_link()` function like so:

```
	/**
	 * Outputs a notice that the current post item is pointed to a custom URL.
	 *
	 * @return void
	 */
	public static function notify_of_external_link() {
		?>
		<div class="notice updated" id="page-links-to-notice"><p><?php _e( '<strong>Note</strong>: This content is pointing to a custom URL. Use the &#8220;Page Links To&#8221; box to change this behavior.', 'page-links-to' ); ?></p></div>
		<?php

		// verify we are using WP5+ and the block editor before generating our own block editor (Gutenberg) admin notices
		global $current_screen;
		if ( ! isset( $current_screen ) ) {
			$current_screen = get_current_screen();
		}
		$is_admin_user = ( current_user_can( 'administrator' ) ) ? 'true' : 'false';
		if ( method_exists( $current_screen, 'is_block_editor' ) && $current_screen->is_block_editor() ) {
			?>
			<script>
				document.addEventListener('DOMContentLoaded', function (event) {
					const isAdminUser = <?php echo $is_admin_user; ?>;
					if (isAdminUser) console.log('page-links-to: DOM loaded');
					if (wp.data !== undefined) {
						const pltNoticesHandle = 'page-links-to-notice';
						const pltNotices = document.querySelector('#' + pltNoticesHandle);

						const cleanupNoticeContent = function (contentObj) {
							const dismissButton = document.querySelector('#' + pltNoticesHandle + ' button.notice-dismiss');
							if (dismissButton) {
								contentObj.removeChild(dismissButton);
							}
							return contentObj.innerText; // only allows plaintext at this time
						};

						const pltNoticeContent = cleanupNoticeContent(pltNotices);

						if (pltNotices.classList.contains('notice-error')) {
							if (isAdminUser) console.log('page-links-to: error notice added');
							wp.data.dispatch('core/notices').createErrorNotice(pltNoticeContent, {isDismissible: true, id: pltNoticesHandle});
						} else if (pltNotices.classList.contains('notice-warning')) {
							if (isAdminUser) console.log('page-links-to: warning notice added');
							wp.data.dispatch('core/notices').createWarningNotice(pltNoticeContent, {isDismissible: true, id: pltNoticesHandle});
						} else if (pltNotices.classList.contains('notice')) {
							if (isAdminUser) console.log('page-links-to: info notice added');
							wp.data.dispatch('core/notices').createInfoNotice(pltNoticeContent, {isDismissible: true, id: pltNoticesHandle});
						}
					}
				});
			</script>
			<?php
		}
	}
```

**Comment by dhuyck** [comment]
Glad I could contribute! We love the single-purpose-ness of the plugin, and it gracefully solves a need we have in our multisite deployment. We have distributed admin users across our college campus, and a simple, intuitive UI like this one means fewer training hours for our departmental admins and other frequent editors. I look forward to upgrading to a fully-gutenbergged version instead of my hacked and patched version!
