### ISSUE TITLE
new tab 

### ISSUE THREAD

**Issue by kinoterapia** [markjaquith/page-links-to#60]
when i press the link it doesnt open in a new tab

**Comment by hemmie85** [comment]
same here, could somebody help us out. Thank you very much....

**Comment by Triode123** [comment]
Hi there
Look for the image that has text within it that says: "Past Times" on this page
http://monotwin.co.uk/test-page/

The page links to plugin worked until I started using it in conjunction with WPBakery.  Specifically the link is still redirected, it's just not creating a new tab.

Many thanks for your time

**Comment by markjaquith** [comment]
This should be fixed in version 3.3.0
