### ISSUE TITLE
Apply only on specific Post Types

### ISSUE THREAD

**Issue by ramiy** [markjaquith/page-links-to#65]
I use this plugin in many sites. Great work @markjaquith !

My problem is that in sites with multiple Post Types I see the metabox in **all** the post types although I need it only in one Post Type.

Any chance the plugin will have a setting page with a list of available Post Types where the user can select in which Post Types the metabox should be displayed?

![wordpress](https://user-images.githubusercontent.com/576623/53492682-29170c00-3aa2-11e9-93fa-29ac3efe8ca7.png)

**Comment by claytoncollie** [comment]
I think you are looking for this filter. 

https://github.com/markjaquith/page-links-to/blob/master/classes/plugin.php#L493

**Comment by ramiy** [comment]
Why using code when we can create a dashboard UI for this?.

**Comment by MadtownLems** [comment]
> Why using code when we can create a dashboard UI for this?.

If every tweak-able functionality of every plugin used a custom dashboard UI for controlling settings, the dashboard would be a mess.

Additionally, using filters instead of dashboard UIs make it a lot easier for people running MultiSite to control functionality across a network of sites.

**Comment by markjaquith** [comment]
I'm working on an add-on plugin that'll contain extra functionality like this. I don't want to overburden this humble plugin.
