### ISSUE TITLE
Option to disable "new tab" feature for AMP Compatibility

### ISSUE THREAD

**Issue by billerickson** [markjaquith/page-links-to#72]
On an AMP native website, this plugin generates an error on all pages because it loads new-tab.min.js globally.

![screenshot](https://d16rm1n165bd05.cloudfront.net/items/2W3x1K421U0K3j0r1Q2G/Screen%20Shot%202019-05-09%20at%202.03.36%20PM.png?X-CloudApp-Visitor-Id=78955b2d79e4b4c9650076a91b4db727&v=ffdf2b5d)

It would be great if I could disable the new tab feature with a filter:

```
add_filter( 'cws_links_to_new_tab', '__return_false' );
```

Which would remove the option from the metabox and not enqueue the JS.

I also think it's worth considering a way to only enqueue the JS file if necessary. On `save_post`, if the current Page Links To post has "new tab" checked, set an option to true.  Before enqueueing the JS, check the option to make sure there is at least one link in the site that has that option checked so the script is necessary.

I'm currently using this to disable the JS globally. The "New Tab" checkbox still appears (which isn't ideal because it won't work), but this particular site doesn't need that feature so it's not an issue:

```
add_action( 'wp_enqueue_scripts', function() { wp_dequeue_script( 'page-links-to' ); }, 20 );
```

**Comment by markjaquith** [comment]
If random script tags are not allowed, and your AMP plugin doesn't have the ability to "take care" of them, don't you run into this issue **all the time**?

**Comment by billerickson** [comment]
Yes, the [official AMP plugin](https://wordpress.org/plugins/amp/) only notifies you of validation errors (ie: JS files loading), it doesn't disable them for you. 

This issue does happen often when installing plugins, but is usually not difficult to resolve. If the JS were essential to the plugin, the plugin won't work on an AMP site anyway so I build the feature custom. If the JS isn't essential to our needs, I can dequeue it or use a filter to prevent JS from loading.

**Comment by markjaquith** [comment]
Okay, that makes sense.
