### ISSUE TITLE
Version released today broke Avada's Fusion Builder

### ISSUE THREAD

**Issue by jvborne** [markjaquith/page-links-to#74]
Using the Avada theme the update 3.10 released just now, broke the Avada theme fusion builder. I rolled back to the 3.01 version. All is well for now.

**Comment by jvborne** [comment]
![image](https://user-images.githubusercontent.com/5993450/57486350-f5174e80-727b-11e9-9b4a-df688c1e3fce.png) Attached warning message

**Comment by jvborne** [comment]
Happened on three different Avada themed sites

**Comment by bloukingfisher** [comment]
I can confirm the same happened on an Avada themed site with Fusion Builder for me. We upgraded to Wordpress 5.2 around the same time so thought it might have been that, but eventually tracked it down to the 3.10 version of this plugin.

**Comment by markjaquith** [comment]
Thanks for the reports @jvborne and @bloukingfisher!

I just verified that the fix for a different issue fixed this issue as well. I'm going to push out a quick bugfix release now. (it will be 3.0.1).

**Comment by markjaquith** [comment]
Correction: new version will be **3.1.1**

**Comment by bloukingfisher** [comment]
Thanks for the quick response @markjaquith !
