### ISSUE TITLE
I does not work with WP 5.2.2

### ISSUE THREAD

**Issue by shokkky8808** [markjaquith/page-links-to#79]
Since WP last update link to does not allow to either make changes in an existing URL, or to add a completely new one in a new page.

**Comment by markjaquith** [comment]
@shokkky8808 Are you still having this issue?

**Comment by shokkky8808** [comment]
Nop. ThxJavier Fernández M.+34 607 785 485
-------- Mensaje original --------De: Mark Jaquith <notifications@github.com> Fecha: 18/11/19  19:15  (GMT+01:00) Para: markjaquith/page-links-to <page-links-to@noreply.github.com> Cc: shokkky8808 <javiercfm@gmail.com>, Mention <mention@noreply.github.com> Asunto: Re: [markjaquith/page-links-to] I does not work with WP 5.2.2 (#79) @shokkky8808 Are you still having this issue?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/markjaquith/page-links-to/issues/79?email_source=notifications\u0026email_token=AILLYIA6IE3U7ZEQPMO26C3QULLUXA5CNFSM4HZRI5PKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEELMRDI#issuecomment-555141261",
"url": "https://github.com/markjaquith/page-links-to/issues/79?email_source=notifications\u0026email_token=AILLYIA6IE3U7ZEQPMO26C3QULLUXA5CNFSM4HZRI5PKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEELMRDI#issuecomment-555141261",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
