### ISSUE TITLE
Page Links to disappeared

### ISSUE THREAD

**Issue by fsav99** [markjaquith/page-links-to#80]
Page links to disappeared from my posts.  The plugin is still installed and up to date.

**Comment by sawbo99** [comment]
I have a similar problem.  Running WP 5.2.2   Just installed PageLinksTo 3.1.1
On Pages menu I get the additional option to "Add Page Link", and it works fine.
But on Posts there is no new option.  Nor does anything appear when creating/editing a post

Pages Menu Image
![image](https://user-images.githubusercontent.com/53020867/61410965-3f9cf300-a8dd-11e9-96bb-e20e95fe829e.png)

Posts menu image
![image](https://user-images.githubusercontent.com/53020867/61410992-49bef180-a8dd-11e9-9153-36bff7dfe6ef.png)

**Comment by markjaquith** [comment]
Has this been resolved? It shows up for me for Posts in both Classic Editor and the Block Editor:

![Screen Shot 2020-01-03 at 2 44 54 PM](https://user-images.githubusercontent.com/353790/71745288-b13f0e00-2e37-11ea-923b-d502d26586b7.png)
![Screen Shot 2020-01-03 at 2 44 36 PM](https://user-images.githubusercontent.com/353790/71745289-b308d180-2e37-11ea-9488-47471ff87de0.png)
