### ISSUE TITLE
Quick Add JS Conflict with MetaSlider Pro & Possibly Others

### ISSUE THREAD

**Issue by KZeni** [markjaquith/page-links-to#83]
I went to add a YouTube slide via MetaSlider Pro. This involves opening the media library popup and then going to the YouTube item on the left. This then loads `/wp-admin/media-upload.php?chromeless=1&tab=youtube` via an iframe.

Unfortunately, it appears that quick-add.min.js adds itself to this iframe's content while `window.pltVars` hasn't been set for the page in the iframe. This results in the following JavaScript error:
```
[Error] TypeError: undefined is not an object (evaluating 'window.pltVars.fancyUrls')
	(anonymous function) (quick-add.min.js:62)
	i (jquery.js:2:27368)
	fireWith (jquery.js:2:28123)
	ready (jquery.js:2:29926)
	J (jquery.js:2:30282)
```

This results in the YouTube media selection not working due to the JS error preventing the parsing of the YouTube URL and then being able to be added as content.

I'd imagine a fix would be to either:

- Make it so this script isn't called on a page like media-upload.php (unless it should be & I'm just unfamiliar with this aspect of the plugin)
- Make it so `window.pltVars` is checked to see if it exists before then trying to access `window.pltVars.fancyUrls`

Otherwise, I don't think having it check for a parent when checking for `window.pltVars` (just in case its in an iframe where the parent has this value) would make too much sense, but maybe it does.

**Comment by KZeni** [comment]
Actually, I'm seeing
```
if (undefined === window.pltVars) {
	return;
}
```
is part of the first `// Copy to clipboard.` code block in `js/quick-add.min.js`, but it then isn't in the separate `// Quick Add.` code block which is then encountering this error.

So another possible fix would be to add
```
if (undefined === window.pltVars) {
	return;
}
```
to the start of the `// Quick Add` block.

I've done the latter and I can confirm that this resolves the conflict with MetaSlider Pro and adding YouTube slides.

**Comment by KZeni** [comment]
I could propose a PR with a fix, but I figured it'd be best for you to choose the preferred fix and implement it in a quicker & simpler fashion (I don't have a JSX compiler setup at the moment [or at least one that matches this plugin's setup], etc.)

**Comment by nachovz** [comment]
Something similar happens in my current installation: WP 5.2.2, Classic Editor. In my particular case, it only happens to any user role **but** the Administrator. I hope this helps.

**Comment by arcticmouse** [comment]
the same issue happens for me in role Author. i don't use metaslider pro but i do use classic editor.

**Comment by markjaquith** [comment]
The latest release should fix this issue!
