### ISSUE TITLE
Page Links To & Gutenberg

### ISSUE THREAD

**Issue by TwisterMc** [markjaquith/page-links-to#84]
In the classic editor, _Page Links To_ is in its own meta box at the bottom of the post with a title of _Page Links To_.

In Gutenberg, it's tied into the _Status & Visibility_ panel and labeled _Custom Permalink_. This is confusing for clients as _Custom Permalink_ sounds like they get to change the WordPress post's permalink as they're use to doing when in fact their redirecting their users away from the content.

Additionally, Open in new tab makes them think that all links in this post are going to open in a new tab. This is all very confusing for them.

I propose that _Page Links To_ moves out of the _Status and Visibility_ panel and into its own panel. 

I get why it's where it is today, but it's confusing users.

**Comment by markjaquith** [comment]
> I get why it's where it is today, but it's confusing users.

I agree. I tried to take a minimalist UI approach and work it into the existing UI, but it turns out to have been too-clever. People expect plugins to add UI, not subtly change existing UI (there are exceptions, of course).

I'm going to work on moving it into its own panel.

**Comment by claytoncollie** [comment]
@markjaquith Checked out this branch and it looks on default Page and Post post types. I like this UI better as well in case the install has a mixture of Classic editor screens and Block editor screens. Allows the user to relate back and forth. I also like it in case any other linking options are added to the metabox.
