### ISSUE TITLE
Gutenberg AMP / Page Links To intertwined.

### ISSUE THREAD

**Issue by TwisterMc** [markjaquith/page-links-to#85]
If we choose not to make the updates in #84, I'd like to let you know that when the [AMP](https://wordpress.org/plugins/amp/) plugin is enabled on a site, it inserts itself between the _Custom Permalink_ option and the URL & _Open in a new tab_ option.

<img width="269" alt="Screen Shot 2019-08-02 at 9 27 50 AM" src="https://user-images.githubusercontent.com/46997/62377167-e8fffd80-b507-11e9-875d-be3b0cdafdb1.png">

It's good to note that if I un-check _Custom Permalink_ and re-check it, then all fields are grouped together as I'd expect. Just seems to happen the first time.

**Comment by markjaquith** [comment]
The latest release of the plugin groups those components together. Thanks for the report!
