### ISSUE TITLE
can not save custom link in my post type

### ISSUE THREAD

**Issue by jaybarad** [markjaquith/page-links-to#91]
when I try to save or edit my post type with adding a custom link it will not save that custom link all other thing relates to post type was saved but the custom link remains blank. please help me what I am wrongdoing in it. I am using your latest version plugin and WordPress version was latest. If I am saving to post and pages it will work no issues in it but if I add in post type then it will not save.

**Comment by markjaquith** [comment]
@jaybarad Do you still experience this issue with the latest version?

**Comment by Datnia** [comment]
@markjaquith Hi, I'm experiencing this issue as well. The plugin works with the default page and post types but not custom post types (currently using v3.2.1).

**Comment by webdevid** [comment]
same with me.. work in post but not in CPT.. @markjaquith

**Comment by Datnia** [comment]
@webdevid downgrading to v3.0.1 worked for me

**Comment by brianpurkiss** [comment]
Saving a link is working for me on a custom post type that does not have Gutenberg enabled. 

It doesn't work when I have the Gutenberg editor enabled.

**Comment by markjaquith** [comment]
Thanks for your patience everyone. I have a fix for this issue and it will go out in the next minor release.

I verified an issue where a custom post type has REST API support (and thus uses the Block Editor) but does not have `custom-fields` support. I was already adding `custom-fields` support for these posts types on the fly, but had neglected to do so when the REST API was initializing. So it could send the data for saving, bu the REST API was ignoring it.

It's working for me now. Here's the custom post type code I used to test:


```php
<?php

function register_things_custom_post_type() {
	$args = array(
		'label'                 => __( 'Thing', 'text_domain' ),
		'supports'              => array( 'title', 'editor' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'show_in_rest'          => true, // This makes it show up in the block editor.
	);
	register_post_type( 'thing', $args );
}

add_action( 'init', 'register_things_custom_post_type', 0 );
```
