### ISSUE TITLE
Javascript error on Editor Role

### ISSUE THREAD

**Issue by pedromiguelmartins** [markjaquith/page-links-to#92]
Hi!
I have a error in using your plugin. What is happening is that I am editing an article in with a Role Editor, I have permanently a JavaScript error that I transcribe. This error does not arise when I am with Role administrator.

> Uncaught TypeError: Cannot read property 'fancyUrls' of undefined
>     at HTMLDocument.<anonymous> (quick-add.jsx:52)
>     at i (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.2.3:2)
>     at Object.fireWith [as resolveWith] (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.2.3:2)
>     at Function.ready (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.2.3:2)
>     at HTMLDocument.J (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.2.3:2)
> 

This JavaScript error is preventing other plugins from working. Can you help?

**Comment by markjaquith** [comment]
Thanks for your report! I’ll look into this.

**Comment by icanbury** [comment]
I want to second this.  I'm experiencing this as well when logged in as Author.

**Comment by pedromiguelmartins** [comment]
Hi Mark!
Have you had a chance to verify this error?

**Comment by pedromiguelmartins** [comment]
Hey Mark! Thanks for the fixing. Excellent work.

**Comment by markjaquith** [comment]
@pedromiguelmartins great! Thanks for verifying the fix.
