### ISSUE TITLE
Cannot read "links_to" of undefined

### ISSUE THREAD

**Issue by xpec-rojas** [markjaquith/page-links-to#93]
If I enable this plugin in gutenberg and add an external links, then the editor get broken and shows me:

![image](https://user-images.githubusercontent.com/30267047/68410223-6619bf00-0156-11ea-98e6-020e48e5669c.png)

![image](https://user-images.githubusercontent.com/30267047/68410161-48e4f080-0156-11ea-8884-87c6cac0e9b9.png)

WordPress 5.2.4

**Comment by markjaquith** [comment]
@xpec-rojas I believe this error should be fixed now. Can you confirm?

**Comment by markjaquith** [comment]
@xpec-rojas Thanks for the report. I believe this was fixed. Please re-open if you're still experiencing this issue.
